const khodams = [
    { name: "Khodam Si Jangkrik Ngakak", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Si Cacing Berkokok", image: "https://placeimg.com/200/200/people" },
    { name: "Khodam Buaya Guling-Guling", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Nasi Goreng Ajaib", image: "https://placeimg.com/200/200/tech" },
    { name: "Khodam Kucing Sembunyi", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kuda Lari Cepat", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Pahlawan Opor Ayam", image: "https://placeimg.com/200/200/food" },
    { name: "Khodam Si Jari Goyang", image: "https://placeimg.com/200/200/people" },
    { name: "Khodam Gajah Sembarangan", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Lalat Terbang Ngakak", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Si Kucing Berlari", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Si Tawon Mendengus", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Dewa Terbang Tinggi", image: "https://placeimg.com/200/200/people" },
    { name: "Khodam Rusa Mencari Arah", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Kupu-Kupu Terkemuka", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Ayam Penjelajah", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Katak Berjoget", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Si Belut Licin", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Lumba-Lumba Lincah", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Gajah Berenang", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Semut Pemberani", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Gigi Terancam", image: "https://placeimg.com/200/200/people" },
    { name: "Khodam Kambing Berlari", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Kucing Suka Tidur", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Singa Menggigit", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Komodo Tertidur", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Listrik Mengalir", image: "https://placeimg.com/200/200/tech" },
    { name: "Khodam Domba Menyanyi", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kelinci Lincah", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kucing Malam", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Buaya Berbaring", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kuda Berloncatan", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Rusa Menyamar", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Elang Terbang", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Ular Berbisa", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Hiu Mengamuk", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Capung Terbang", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Kumbang Terbang", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Orangutan Berkendara", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Buaya Pura-Pura Tidur", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Lumba-Lumba Menghancurkan", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kucing Ngeong", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Gajah Dengan Kaki Besar", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Tikus Berjalan Di Sirkuit", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kuda Kembar", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kelinci Hopping", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Domba Suka Makan", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Macan Kuno", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Si Panda Lucu", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Si Bebek Bertopi", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Angsa Berkicau", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kupu-Kupu Sakit", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Serigala Mencakar", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kuda Laut", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Bebek Gede", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Cumi-Cumi Terbang", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Cacing Terluka", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kelelawar Malam", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kambing Merah", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Ikan Paus Besar", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Unta Sabar", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Rusa Berenang", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Ayam Seribu", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Cendawan Besar", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Lumba-Lumba Siluman", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kuda Meledak", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Harimau Sabar", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Buaya Pemandu", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Si Kodok Mencari", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Serigala Siluman", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kuda Raksasa", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Beruang Kutub", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Singa Raja", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kelelawar Misterius", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Gajah Terkendali", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kambing Hitam", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Cacing Hitam", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Cendawan Ajaib", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Lumba-Lumba Sabar", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Si Rusa", image: "https://placeimg.com/200/200/nature" },
    { name: "Khodam Lalat Terbang Sambil Tertawa", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kucing Raksasa", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Unta Siluman", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Singa Berbahaya", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Buaya Hebat", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Kuda Tersenyum", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Komodo Dewa", image: "https://placeimg.com/200/200/animals" },
    { name: "Khodam Ayam Siluman", image: "https://placeimg.com/200/200/animals" }
];

function generateKhodam() {
    const randomIndex = Math.floor(Math.random() * khodams.length);
    const khodam = khodams[randomIndex];
    
    document.getElementById("khodam-name").innerText = khodam.name;
    document.getElementById("khodam-photo").src = khodam.image;
}
